#
# docker build --file Dockerfile.perl-5.26.2 --tag keedi/perl-5.26.2 .
#
#   docker run -it --rm --name=con-extract keedi/perl-5.26.2:latest /bin/bash
#       tar cvzf /root/perl-5.26.2-site_perl.tar.gz -C /usr/local/lib/perl5/site_perl 5.26.2
#
#   docker cp con-extract:/root/perl-5.26.2-site_perl.tar.gz ./static/
#
FROM perl:5.26.2-slim-threaded
LABEL maintainer="Keedi Kim <keedi@cpan.org>"

#
# for fast build
#
COPY static/perl-5.26.2-site_perl.tar.gz ./
RUN tar xvzf perl-5.26.2-site_perl.tar.gz -C /usr/local/lib/perl5/site_perl

#
# preparing to build
#
ENV DEBIAN_FRONTEND=noninteractive
RUN true \
    && apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y --no-install-recommends \
        apt-utils

#
# build tool & lib
#
RUN true \
    && apt-get install -y --no-install-recommends \
        gcc \
        make \
        netbase \
        libc6-dev

#
# Term::ReadLine
#
RUN true \
    && apt-get install -y --no-install-recommends \
        libncursesw5-dev \
        libreadline-dev \
    && cpanm \
        Term::ReadLine \
        Term::ReadLine::Gnu \
    && cpanm --notest Term::ReadLine::Perl

#
# TLS/SSL
#
RUN true \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        libssl-dev \
        openssl \
        zlib1g-dev \
    && cpanm \
        Mozilla::CA \
        Net::SSLeay \
        IO::Socket::SSL \
    && NO_NETWORK_TESTING=1 cpanm \
        Net::HTTP

#
# DBI & DBD::*
#
RUN true \
    && apt-get install -y --no-install-recommends \
        libmariadbclient-dev \
        libpq-dev \
    && cpanm \
        DBI \
        DBD::SQLite \
        DBD::mysql \
        DBD::Pg

#
# Minion & Mojolicious
#
RUN true \
    && cpanm \
        Mojolicious \
        Minion \
        Minion::Backend::mysql

#
# Mandatory Module: light-weight
#
RUN true \
    && cpanm \
        Capture::Tiny \
        Class::Tiny \
        DateTime \
        DateTime::Tiny \
        HTTP::Tiny \
        Log::Log4perl \
        Log::Log4perl::Tiny \
        Path::Tiny \
        Try::Tiny

#
# Mandatory Module: heavy-weight
#
RUN cpanm Moo
RUN cpanm Moose
RUN cpanm DBIx::Class
RUN cpanm DBIx::Class::Schema::Loader
RUN cpanm Plack
RUN cpanm Ubic
RUN cpanm Ubic::Service::Hypnotoad
RUN cpanm Dist::Zilla
RUN true \
    && apt-get install -y \
        git \
        rename \
    && cpanm Dist::Zilla::PluginBundle::DAGOLDEN

#
# cleaning
#
RUN true \
    && savedPackages="ca-certificates libc6 libmariadbclient18 libncursesw5 libpq5 libreadline7 make netbase openssl zlib1g" \
    && apt-mark auto '.*' > /dev/null \
    && apt-mark manual $savedPackages \
    && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
    && rm -fr /var/cache/apt/* /var/lib/apt/lists/* \
    && rm -fr ./cpanm /root/.cpanm /usr/src/perl /tmp/* \
    && rm -fr /root/*.tar.gz

CMD ["bash"]
